/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111768-ga3b434e151-20230815"
#endif /* AVUTIL_FFVERSION_H */
