//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumMedia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Desktop-tc4949r\\e")]
        public string SHAREDFOLDER {
            get {
                return ((string)(this["SHAREDFOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Desktop-tc4949r\\e\\Users\\Movie")]
        public string MOVIEFOLDER {
            get {
                return ((string)(this["MOVIEFOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Desktop-tc4949r\\e\\Users\\Movie\\Photos")]
        public string POSTERFOLDER {
            get {
                return ((string)(this["POSTERFOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb+srv://dallasagsmith:bOosWckeDjoGxxtf@homesevrer.tmigh2b.mongodb.net/test")]
        public string ATLASCONNECTIONSTRING {
            get {
                return ((string)(this["ATLASCONNECTIONSTRING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HomeServer")]
        public string DATABASE {
            get {
                return ((string)(this["DATABASE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700de9a2ae584e24a79d2050b541f34c")]
        public string AZURE_API_KEY {
            get {
                return ((string)(this["AZURE_API_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://albummediacomputervision.cognitiveservices.azure.com/")]
        public string AZURE_API_ENDPOINT {
            get {
                return ((string)(this["AZURE_API_ENDPOINT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\FFMPEG\\Temporary\\")]
        public string TEMPORARYFOLDER {
            get {
                return ((string)(this["TEMPORARYFOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("endpoint=https://album-media-communications.canada.communication.azure.com/;acces" +
            "skey=uaDpV7ZFSAn3HFIwK5ngVwSaJG/9RKBaDY3ztJW3/GxBxluBDfMMWqXq2kfoRpxLO5MPepaUmDe" +
            "zBBGt+AbJjw==")]
        public string EMAIL_CONNECTION_STRING {
            get {
                return ((string)(this["EMAIL_CONNECTION_STRING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoNotReply@7b689d1e-a4c8-47a8-afc1-e068a6098582.azurecomm.net")]
        public string EMAIL_ADDRESS {
            get {
                return ((string)(this["EMAIL_ADDRESS"]));
            }
        }
    }
}
